// Generated by src/cli/instruments.ts from docs/fits-lean and docs/consensus/consensus-bass-seed1.json, docs/consensus/consensus-bass-seed2.json, docs/consensus/consensus-treble-seed1.json, docs/consensus/consensus-treble-seed2.json; do not edit by hand.
// Bellows travel, rails at 0 and 1, drawing apparatus off. The test beside instruments.ts keeps it so.

import type { Instrument } from "./instruments.ts";

export const PRESET_DATA: Readonly<Record<"1348" | "1474" | "1478" | "2739" | "3309" | "3357", Instrument>> = {
  "1348": {
    "name": "1348",
    "bass": {
      "alpha": 0.6181420554591925,
      "piano": 0,
      "forte": 1,
      "mezzoforte": 0.8008620945395729,
      "crescendoRate": 1.0623105165966937,
      "crescendoTarget": 1.0000078688631038,
      "releaseRate": 0.7632389496212869,
      "releaseTarget": 0.0003434748777064496,
      "sforzandoRate": 2.749480259703837,
      "sforzandoTarget": 2.528970277427742,
      "sforzandoAssistRate": 32.44429430168073,
      "tripThreshold": 0.09518247194509726,
      "membraneFillMs": 4.5392808116537156,
      "assistFillMs": 42.690202314386006,
      "valveTailMs": 44.903746673106234,
      "inertiaMs": 0.21093741075814357,
      "leadRows": 0,
      "leadSforzandoOnRows": 0,
      "leadCrescendoRows": 0,
      "leadDriftRows": 0,
      "valveBand": 0.29349631349257405,
      "throughFlowLoad": 0.36483364065004,
      "scaleWarp": 0,
      "stopRestitution": 0.44933103460990265
    },
    "treble": {
      "alpha": 0.6891067771258702,
      "piano": 0,
      "forte": 1,
      "mezzoforte": 0.8255364053046619,
      "crescendoRate": 0.5353852261078158,
      "crescendoTarget": 0.9859495235742441,
      "releaseRate": 0.5751853513541533,
      "releaseTarget": 0.0015733468471030474,
      "sforzandoRate": 2.37664404399365,
      "sforzandoTarget": 3.2562885590641435,
      "sforzandoAssistRate": 27.916637391903382,
      "tripThreshold": 0.09202614077384215,
      "membraneFillMs": 3.3970383855732504,
      "assistFillMs": 36.922817413936286,
      "valveTailMs": 35.69715520303115,
      "inertiaMs": 0.14425868317254747,
      "leadRows": 0,
      "leadSforzandoOnRows": 0,
      "leadCrescendoRows": 0,
      "leadDriftRows": 0,
      "valveBand": 0.7395260962070251,
      "throughFlowLoad": 0.584200785226675,
      "scaleWarp": 0,
      "stopRestitution": 0.7424987675101706
    },
    "provenance": {
      "druid": "jn038xx9588",
      "performer": "Felix Mottl",
      "title": "Wagner, Lohengrin",
      "traces": "round 2",
      "seeds": 2,
      "seedSpread": 0.0002239176736170273,
      "bass": {
        "heldOutRmse": 0.026861168013655283,
        "coverage": 0.8715711662507651,
        "hookArrivals": 0
      },
      "treble": {
        "heldOutRmse": 0.03784656805511667,
        "coverage": 0.947935401855078,
        "hookArrivals": 0
      }
    }
  },
  "1474": {
    "name": "1474",
    "bass": {
      "alpha": 0.9723576171914184,
      "piano": 0,
      "forte": 1,
      "mezzoforte": 0.7445492597793598,
      "crescendoRate": 0.6534022428497224,
      "crescendoTarget": 0.9555617996149143,
      "releaseRate": 0.4676973495536019,
      "releaseTarget": -0.29975110434091723,
      "sforzandoRate": 5.073582908301078,
      "sforzandoTarget": 1.266358089049397,
      "sforzandoAssistRate": 16.10782687043492,
      "tripThreshold": 0.48159817453045106,
      "membraneFillMs": 1.2487360676244634,
      "assistFillMs": 9.76466326412496,
      "valveTailMs": 99.31714363921212,
      "inertiaMs": 20.079390815418684,
      "leadRows": 0,
      "leadSforzandoOnRows": 0,
      "leadCrescendoRows": 0,
      "leadDriftRows": 0,
      "valveBand": 0.902713894106339,
      "throughFlowLoad": 0.04202347137839767,
      "scaleWarp": 0,
      "stopRestitution": 0.20153452940392735
    },
    "treble": {
      "alpha": 0.5802647257081753,
      "piano": 0,
      "forte": 1,
      "mezzoforte": 0.7213156032398343,
      "crescendoRate": 0.4301214389677657,
      "crescendoTarget": 0.9986778227181623,
      "releaseRate": 0.8712051701348331,
      "releaseTarget": 0.00795264640378662,
      "sforzandoRate": 2.0445895542052903,
      "sforzandoTarget": 2.997770047048306,
      "sforzandoAssistRate": 15.73358972301251,
      "tripThreshold": 0.10359986435810521,
      "membraneFillMs": 0.09270187508574712,
      "assistFillMs": 2.4401874035601017,
      "valveTailMs": 38.04389084457209,
      "inertiaMs": 1.6879960354829517,
      "leadRows": 0,
      "leadSforzandoOnRows": 0,
      "leadCrescendoRows": 0,
      "leadDriftRows": 0,
      "valveBand": 0.4567588584237611,
      "throughFlowLoad": 0.0008751092636158502,
      "scaleWarp": 0,
      "stopRestitution": 0.1541321868646483
    },
    "provenance": {
      "druid": "ns598kr8616",
      "performer": "Olga Samaroff",
      "title": "Liszt, Tannhäuser march",
      "traces": "round 2",
      "seeds": 2,
      "seedSpread": 0.0005918630964474314,
      "bass": {
        "heldOutRmse": 0.023476761308056565,
        "coverage": 0.941290938463798,
        "hookArrivals": 118
      },
      "treble": {
        "heldOutRmse": 0.04378585036846641,
        "coverage": 0.9472546839267356,
        "hookArrivals": 128
      }
    }
  },
  "1478": {
    "name": "1478",
    "bass": {
      "alpha": 1.45979380819243,
      "piano": 0,
      "forte": 1,
      "mezzoforte": 0.7290488029010807,
      "crescendoRate": 0.8288199912661887,
      "crescendoTarget": 0.8664236646145484,
      "releaseRate": 0.8644118520741022,
      "releaseTarget": -0.5495206021964517,
      "sforzandoRate": 0.9159207849296487,
      "sforzandoTarget": 3.003597579637957,
      "sforzandoAssistRate": 61.89641278462377,
      "tripThreshold": 0.2602751742777735,
      "membraneFillMs": 23.23518520008742,
      "assistFillMs": 35.35629319118526,
      "valveTailMs": 135.82310861240424,
      "inertiaMs": 0.07714786086918177,
      "leadRows": 0,
      "leadSforzandoOnRows": 0,
      "leadCrescendoRows": 0,
      "leadDriftRows": 0,
      "valveBand": 0.11484217008700302,
      "throughFlowLoad": 0.053889240514714117,
      "scaleWarp": 0,
      "stopRestitution": 0.7702272134258219
    },
    "treble": {
      "alpha": 0.919937908613848,
      "piano": 0,
      "forte": 1,
      "mezzoforte": 0.7228701381024293,
      "crescendoRate": 0.5459499283003303,
      "crescendoTarget": 0.896059974032681,
      "releaseRate": 0.7057687920228283,
      "releaseTarget": -0.15525783065117768,
      "sforzandoRate": 1.366846530607732,
      "sforzandoTarget": 3.2996549887955835,
      "sforzandoAssistRate": 37.84091815820472,
      "tripThreshold": 0.38670421992392245,
      "membraneFillMs": 1.8550800942506325,
      "assistFillMs": 14.94880773725738,
      "valveTailMs": 108.84347326477256,
      "inertiaMs": 15.285447782171838,
      "leadRows": 0,
      "leadSforzandoOnRows": 0,
      "leadCrescendoRows": 0,
      "leadDriftRows": 0,
      "valveBand": 0.48461494280342676,
      "throughFlowLoad": 0.20750033688981703,
      "scaleWarp": 0,
      "stopRestitution": 0.049974738001907666
    },
    "provenance": {
      "druid": "ym773gh2267",
      "performer": "Olga Samaroff",
      "title": "Grieg, concerto in A minor",
      "traces": "round 2",
      "seeds": 2,
      "seedSpread": 0.0007327925899303367,
      "bass": {
        "heldOutRmse": 0.021908897831156498,
        "coverage": 0.9778136144858599,
        "hookArrivals": 85
      },
      "treble": {
        "heldOutRmse": 0.05288894098743787,
        "coverage": 0.9769417886883991,
        "hookArrivals": 156
      }
    }
  },
  "2739": {
    "name": "2739",
    "bass": {
      "alpha": 0.7039798394811462,
      "piano": 0,
      "forte": 1,
      "mezzoforte": 0.8716408771590564,
      "crescendoRate": 1.107051793302975,
      "crescendoTarget": 0.8769280435513687,
      "releaseRate": 0.8268067457217432,
      "releaseTarget": -0.2155739245974548,
      "sforzandoRate": 2.232742864718177,
      "sforzandoTarget": 2.9876833101348867,
      "sforzandoAssistRate": 22.54227508082667,
      "tripThreshold": 0.1283082887093988,
      "membraneFillMs": 6.2315639291860485,
      "assistFillMs": 13.536124486997771,
      "valveTailMs": 53.08482002575696,
      "inertiaMs": 0.08964620264754422,
      "leadRows": 0,
      "leadSforzandoOnRows": 0,
      "leadCrescendoRows": 0,
      "leadDriftRows": 0,
      "valveBand": 0.012006686137678324,
      "throughFlowLoad": 0.2988444034148545,
      "scaleWarp": 0,
      "stopRestitution": 0.8994561805160212
    },
    "treble": {
      "alpha": 0.6356357910772995,
      "piano": 0,
      "forte": 1,
      "mezzoforte": 0.8027980985524217,
      "crescendoRate": 0.45171492412057995,
      "crescendoTarget": 0.9692488265455047,
      "releaseRate": 0.5531830478605383,
      "releaseTarget": -0.03108901718933902,
      "sforzandoRate": 3.0274318897803973,
      "sforzandoTarget": 3.0490344085657424,
      "sforzandoAssistRate": 22.678546895093344,
      "tripThreshold": 0.03899367861924057,
      "membraneFillMs": 31.38089055927044,
      "assistFillMs": 33.98423822388136,
      "valveTailMs": 24.931941731042734,
      "inertiaMs": 0.009014303330209583,
      "leadRows": 0,
      "leadSforzandoOnRows": 0,
      "leadCrescendoRows": 0,
      "leadDriftRows": 0,
      "valveBand": 0.860700703840978,
      "throughFlowLoad": 0.0012586312511110385,
      "scaleWarp": 0,
      "stopRestitution": 0.8883643786810126
    },
    "provenance": {
      "druid": "ws250sr1272",
      "performer": "Claude Debussy",
      "title": "Préludes",
      "traces": "round 2",
      "seeds": 2,
      "seedSpread": 0.0056910706887438114,
      "bass": {
        "heldOutRmse": 0.026776881348440557,
        "coverage": 0.7778951146450215,
        "hookArrivals": 4
      },
      "treble": {
        "heldOutRmse": 0.025743664024831338,
        "coverage": 0.5167101503292334,
        "hookArrivals": 8
      },
      "note": "The drawing is faint, and the treble rests on the P.P. rule for much of the roll."
    }
  },
  "3309": {
    "name": "3309",
    "bass": {
      "alpha": 1.4487719374720025,
      "piano": 0,
      "forte": 1,
      "mezzoforte": 0.7860609385458919,
      "crescendoRate": 1.543792184128698,
      "crescendoTarget": 0.9078690568254827,
      "releaseRate": 0.6334807522125586,
      "releaseTarget": -0.47558184284933336,
      "sforzandoRate": 1.0276053879007425,
      "sforzandoTarget": 3.2882715611927575,
      "sforzandoAssistRate": 19.234236274486857,
      "tripThreshold": 0.21157976546056081,
      "membraneFillMs": 0.2287087349667691,
      "assistFillMs": 11.48808805127564,
      "valveTailMs": 61.720230845307334,
      "inertiaMs": 15.909413137020096,
      "leadRows": 0,
      "leadSforzandoOnRows": 0,
      "leadCrescendoRows": 0,
      "leadDriftRows": 0,
      "valveBand": 0.12254338624248524,
      "throughFlowLoad": 0.14448992875916272,
      "scaleWarp": 0,
      "stopRestitution": 0.8410688053716382
    },
    "treble": {
      "alpha": 1.210332828791787,
      "piano": 0,
      "forte": 1,
      "mezzoforte": 0.7851474498091562,
      "crescendoRate": 0.7298096680227272,
      "crescendoTarget": 0.9276154385428199,
      "releaseRate": 0.7419009164444451,
      "releaseTarget": -0.28125553209711046,
      "sforzandoRate": 1.9640218397454712,
      "sforzandoTarget": 2.382936648879012,
      "sforzandoAssistRate": 31.27274245370196,
      "tripThreshold": 0.34693953725915716,
      "membraneFillMs": 11.642669807442063,
      "assistFillMs": 19.804966144077433,
      "valveTailMs": 110.35419544877158,
      "inertiaMs": 18.99821097717847,
      "leadRows": 0,
      "leadSforzandoOnRows": 0,
      "leadCrescendoRows": 0,
      "leadDriftRows": 0,
      "valveBand": 0.18361775175872705,
      "throughFlowLoad": 0.11929898214336279,
      "scaleWarp": 0,
      "stopRestitution": 0.10067932675551175
    },
    "provenance": {
      "druid": "jq774vx6544",
      "performer": "Wilhelm Backhaus",
      "title": "Schubert, Militärmarsch",
      "traces": "round 2",
      "seeds": 2,
      "seedSpread": 0.0007325854813431953,
      "bass": {
        "heldOutRmse": 0.026673606323132745,
        "coverage": 0.9277400191310476,
        "hookArrivals": 149
      },
      "treble": {
        "heldOutRmse": 0.0409733982195671,
        "coverage": 0.9262246387756129,
        "hookArrivals": 107
      }
    }
  },
  "3357": {
    "name": "3357",
    "bass": {
      "alpha": 1.0979914004958353,
      "piano": 0,
      "forte": 1,
      "mezzoforte": 0.7749137086337241,
      "crescendoRate": 0.8179372302453365,
      "crescendoTarget": 0.8114051693021003,
      "releaseRate": 1.0391063904325435,
      "releaseTarget": -0.2625871483081846,
      "sforzandoRate": 1.532616138520558,
      "sforzandoTarget": 3.2040144027154716,
      "sforzandoAssistRate": 26.365830856651765,
      "tripThreshold": 0.3381304772528676,
      "membraneFillMs": 3.283190963240085,
      "assistFillMs": 10.608756977764019,
      "valveTailMs": 78.03539888280744,
      "inertiaMs": 35.24559258031255,
      "leadRows": 0,
      "leadSforzandoOnRows": 0,
      "leadCrescendoRows": 0,
      "leadDriftRows": 0,
      "valveBand": 0.2954739587547933,
      "throughFlowLoad": 0.17193001949372927,
      "scaleWarp": 0,
      "stopRestitution": 0.4525526901104073
    },
    "treble": {
      "alpha": 1.422026851492025,
      "piano": 0,
      "forte": 1,
      "mezzoforte": 0.7740739097939626,
      "crescendoRate": 0.7586288151337245,
      "crescendoTarget": 0.8592074279988632,
      "releaseRate": 0.4437408100669658,
      "releaseTarget": -0.4898388438141097,
      "sforzandoRate": 0.7381492475823833,
      "sforzandoTarget": 3.5059620870598724,
      "sforzandoAssistRate": 43.43740461901972,
      "tripThreshold": 0.1725419723423515,
      "membraneFillMs": 1.1932161944703508,
      "assistFillMs": 43.09251836080794,
      "valveTailMs": 61.942110318750636,
      "inertiaMs": 19.30477676125944,
      "leadRows": 0,
      "leadSforzandoOnRows": 0,
      "leadCrescendoRows": 0,
      "leadDriftRows": 0,
      "valveBand": 0.5535202977976877,
      "throughFlowLoad": 0.1577032066314934,
      "scaleWarp": 0,
      "stopRestitution": 0.1602306286851924
    },
    "provenance": {
      "druid": "kw215gn3365",
      "performer": "Hubert Flohr",
      "title": "Raff, Cachoucha",
      "traces": "round 2",
      "seeds": 2,
      "seedSpread": 0.00029124956564918064,
      "bass": {
        "heldOutRmse": 0.02492029912319349,
        "coverage": 0.9724275043762722,
        "hookArrivals": 47
      },
      "treble": {
        "heldOutRmse": 0.016336303663438682,
        "coverage": 0.9442213403670524,
        "hookArrivals": 39
      },
      "note": "The strokes are wide with a dark edge on the soft side, which the tracer rides, so levels may sit a few hundredths off, consistently."
    }
  }
};

export const CONSENSUS_DATA: Instrument = {
  "name": "consensus",
  "bass": {
    "alpha": 1.209986217373252,
    "piano": 0,
    "forte": 1,
    "mezzoforte": 0.7726768130299547,
    "crescendoRate": 1.1536616595286484,
    "crescendoTarget": 0.9317683147287303,
    "releaseRate": 0.46310604727737614,
    "releaseTarget": -0.6928888276617435,
    "sforzandoRate": 2.6168414639312054,
    "sforzandoTarget": 1.9942822225328105,
    "sforzandoAssistRate": 13.310763916908268,
    "tripThreshold": 0.33910056523642723,
    "membraneFillMs": 0.4101970044166362,
    "assistFillMs": 4.73759875115387,
    "valveTailMs": 75.29481182512296,
    "inertiaMs": 14.810525816737854,
    "leadRows": 0,
    "leadSforzandoOnRows": 0,
    "leadCrescendoRows": 0,
    "leadDriftRows": 0,
    "valveBand": 0.010203071444105255,
    "throughFlowLoad": 0.1243177102939653,
    "scaleWarp": 0,
    "stopRestitution": 0.9
  },
  "treble": {
    "alpha": 1.1013379272818224,
    "piano": 0,
    "forte": 1,
    "mezzoforte": 0.7648670193203597,
    "crescendoRate": 0.6064714631079782,
    "crescendoTarget": 0.9419208118823885,
    "releaseRate": 0.739896901884261,
    "releaseTarget": -0.15319056894432775,
    "sforzandoRate": 1.2017420477815761,
    "sforzandoTarget": 3.1717083958378653,
    "sforzandoAssistRate": 54.019960565663844,
    "tripThreshold": 0.06812519187559984,
    "membraneFillMs": 2.995857640764438,
    "assistFillMs": 38.574635979997765,
    "valveTailMs": 29.23732704833253,
    "inertiaMs": 22.567746180134144,
    "leadRows": 0,
    "leadSforzandoOnRows": 0,
    "leadCrescendoRows": 0,
    "leadDriftRows": 0,
    "valveBand": 0.011061342387999386,
    "throughFlowLoad": 0.18446579814306213,
    "scaleWarp": 0,
    "stopRestitution": 0.2266829395652791
  },
  "provenance": {
    "traces": "round 2",
    "seeds": 2,
    "seedSpread": 0.00021444822984524603,
    "bass": {
      "heldOutRmse": 0.0680818580503287
    },
    "treble": {
      "heldOutRmse": 0.056986911303149916
    },
    "pooled": {
      "1348": {
        "bass": 0.10051288397822059,
        "treble": 0.08166904808507501
      },
      "1474": {
        "bass": 0.05281197585762243,
        "treble": 0.06059867667655376
      },
      "1478": {
        "bass": 0.10484745516036709,
        "treble": 0.06283536408878326
      },
      "2739": {
        "bass": 0.036497124766115614,
        "treble": 0.051038499769547156
      },
      "3309": {
        "bass": 0.03432813080974359,
        "treble": 0.05445449208470849
      },
      "3357": {
        "bass": 0.07949357772990288,
        "treble": 0.03132538711423177
      }
    }
  }
};
