# What did the project once believe and later withdraw, and on what grounds?
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX crminf: <http://www.cidoc-crm.org/extensions/crminf/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wt: <https://w3id.org/welte-t100/>
PREFIX property: <https://w3id.org/welte-t100/property/>
PREFIX concept: <https://w3id.org/welte-t100/concept/>
PREFIX logic: <https://w3id.org/welte-t100/logic/>
PREFIX crmsci: <http://www.cidoc-crm.org/extensions/crmsci/>

SELECT ?withdrawn ?grounds ?locator
WHERE {
  ?revision crminf:J3_applied logic:knowledge-revision ;
            crminf:J2_concluded_that ?conclusion ;
            crminf:J1_used_as_premise ?premise .
  ?conclusion crminf:J5_holds_to_be "FALSE" ;
              crminf:J4_that/rdfs:label ?withdrawn .
  ?premise rdfs:label ?grounds .
  ?passage crm:P70_documents ?revision ; wt:locator ?locator .
}
