# Which claims descend from Anhang 13, a T-100 plate redrawn from a T-98 manual?
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX crminf: <http://www.cidoc-crm.org/extensions/crminf/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wt: <https://w3id.org/welte-t100/>
PREFIX property: <https://w3id.org/welte-t100/property/>
PREFIX concept: <https://w3id.org/welte-t100/concept/>
PREFIX logic: <https://w3id.org/welte-t100/logic/>
PREFIX crmsci: <http://www.cidoc-crm.org/extensions/crmsci/>

SELECT ?claim ?holds ?locator
WHERE {
  ?argument rdfs:label ?claim ;
            wt:definedIn "sources/pfeffer-anhang13.yaml" ;
            crminf:J2_concluded_that ?belief .
  ?belief crminf:J5_holds_to_be ?holds .
  ?passage crm:P70_documents ?argument ; wt:locator ?locator .
}
ORDER BY ?claim
