/**
 * Gather the ablation slices into one table and one fit.
 *
 *   node src/cli/collect.ts scratch/exp-*.json
 *
 * `src/cli/experiments.ts --slice i/n` splits the variants across processes;
 * this puts them back together, writes `docs/experiments.json` and
 * `docs/experiments.md`, and lifts the parameters of the unrestricted pneumatic
 * fit into `docs/fit-pneumatic.json` so the viewer and the residual report have
 * one file to read.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

import type { Agreement } from "../eval/metrics.ts";
import type { Parameters } from "../model/types.ts";
import { pneumaticModel } from "../model/pneumatic.ts";
import { describeTraversals } from "../model/timings.ts";
import type { Half } from "../roll/expression.ts";

type Row = {
  variant: string;
  question: string;
  half: Half;
  params: Parameters;
  train: Agreement;
  test: Agreement;
  seconds: number;
};

// The lean variant pins the terms the ablation shows to be null, which is what the
// headline fit does, and it scores better than leaving them free. Prefer it.
const FULL = "pneumatic, lean";
const FALLBACK = "pneumatic, full";

/** A correlation is null in the file when the model is constant and has no spread. */
function number(value: number | null | undefined, places: number): string {
  return typeof value === "number" && Number.isFinite(value) ? value.toFixed(places) : "—";
}

function markdown(rows: readonly Row[]): string {
  const order = [...new Set(rows.map((row) => row.variant))];
  const cell = (variant: string, half: Half, read: (row: Row) => string): string => {
    const row = rows.find((entry) => entry.variant === variant && entry.half === half);
    return row ? read(row) : "—";
  };

  const table = order
    .map((variant) => {
      const question = rows.find((row) => row.variant === variant)?.question ?? "";
      const bass = cell(variant, "bass", (row) => number(row.test.rmse, 4));
      const treble = cell(variant, "treble", (row) => number(row.test.rmse, 4));
      const bassR = cell(variant, "bass", (row) => number(row.test.correlation, 3));
      const trebleR = cell(variant, "treble", (row) => number(row.test.correlation, 3));
      return `| ${variant} | ${question} | ${bass} | ${treble} | ${bassR} | ${trebleR} |`;
    })
    .join("\n");

  const parameters = pneumaticModel.spec
    .map((entry) => {
      const at = (half: Half): string => {
        const row = rows.find((entry2) => entry2.variant === FULL && entry2.half === half);
        const value = row?.params[entry.name];
        if (value === undefined) return "—";
        const rail = value <= entry.lower + 1e-6 ? " ↓" : value >= entry.upper - 1e-6 ? " ↑" : "";
        return `${Number(value.toPrecision(4))}${rail}`;
      };
      return `| \`${entry.name}\` | ${entry.unit} | ${at("bass")} | ${at("treble")} | ${Number(
        (pneumaticModel.defaults[entry.name] ?? 0).toPrecision(4),
      )} | ${entry.note} |`;
    })
    .join("\n");

  const fraction = (["bass", "treble"] as const)
    .map((half) => {
      const p = rows.find((row) => row.variant === FULL && row.half === half)?.params;
      if (!p) return `| ${half} | — |`;
      const share = ((p.mezzoforte ?? 0) - (p.piano ?? 0)) / ((p.forte ?? 1) - (p.piano ?? 0));
      return `| ${half} | ${share.toFixed(3)} |`;
    })
    .join("\n");

  const travel = (["bass", "treble"] as const)
    .map((half) => {
      const row = rows.find((entry) => entry.variant === FULL && entry.half === half);
      if (!row) return "";
      const lines = describeTraversals(row.params)
        .map((entry) => `| ${entry.span} | ${entry.from} | ${entry.to} | ${entry.ms} |`)
        .join("\n");
      return `\n**${half}**\n\n| span | from | to | ms |\n| --- | ---: | ---: | ---: |\n${lines}\n`;
    })
    .join("");

  return `# Ablation

Held-out error, in units of the roll's printed scale, where 1.0 is the whole P.P. to F.F.
span. Every variant is refitted from scratch, so pinning one choice does not simply deprive
the model of a parameter: the rest move to compensate, and what the table shows is what the
choice costs after the model has done its best without it. Fitting is on alternating
eight-second blocks and the numbers below are on the blocks left out.

Generated by \`src/cli/experiments.ts\`; do not edit by hand.

| variant | question | bass RMSE | treble RMSE | bass r | treble r |
| --- | --- | ---: | ---: | ---: | ---: |
${table}

## Fitted parameters of the unrestricted model

An arrow marks a value resting on its bound, which means the bound and not the roll is
setting it.

| parameter | unit | bass | treble | default | note |
| --- | --- | ---: | ---: | ---: | --- |
${parameters}

## Where the fit puts the Mezzoforte pin

As a fraction of the travel between the fitted rails, which is the form free of the
common-mode drift of the traced line against the printed gridlines. Measured directly off
the roll: 0.627 (bass) and 0.645 (treble), sd 0.002 to 0.003.

| half | fraction of P-to-F travel |
| --- | ---: |
${fraction}

## Travel times implied by the fit

Free travel, ignoring the rails and the Mezzoforte pin, for comparison with midi2exp's
published constants: 2380 ms for P to M.F., 300 ms for the fast crescendo over the same
span, 400 ms for the fast decrescendo from F to P.
${travel}`;
}

function main(): void {
  const paths = process.argv.slice(2).filter((argument) => !argument.startsWith("--"));
  if (paths.length === 0) throw new Error("usage: collect.ts <slice.json>...");

  // Later files re-run earlier variants at higher effort; the first file to carry a
  // (variant, half) wins, so pass the reruns first.
  const seen = new Set<string>();
  const rows = paths
    .flatMap((path) => (JSON.parse(readFileSync(path, "utf8")) as { rows: Row[] }).rows)
    .filter((row) => {
      const key = `${row.variant}\u0000${row.half}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .sort((a, b) => a.variant.localeCompare(b.variant) || a.half.localeCompare(b.half));

  mkdirSync(dirname("docs/experiments.json"), { recursive: true });
  writeFileSync("docs/experiments.json", JSON.stringify({ rows }, null, 2));
  writeFileSync("docs/experiments.md", markdown(rows));

  const full = rows.filter((row) => row.variant === FULL).length > 0
    ? rows.filter((row) => row.variant === FULL)
    : rows.filter((row) => row.variant === FALLBACK);
  if (full.length > 0) {
    writeFileSync(
      "docs/fit-pneumatic.json",
      JSON.stringify(
        { model: pneumaticModel.name, druid: "jq774vx6544", ports: "aperture", results: full },
        null,
        2,
      ),
    );
  }

  console.log(`${rows.length} rows over ${new Set(rows.map((row) => row.variant)).size} variants`);
  console.log("wrote docs/experiments.json, docs/experiments.md, docs/fit-pneumatic.json");
}

// Only when run as a command. These modules hold constants other code imports,
// and several of them start a fit or an ablation, so an import that ran them
// would quietly spend an hour of a machine.
if (import.meta.main) main();
